# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += -I$(srctree)/drivers/power/mmi_charger
EXTRA_CFLAGS += -DUSE_MMI_CHARGER

ifneq ($(filter m y,$(CONFIG_USE_MMI_CHARGER)),)
	EXTRA_CFLAGS += -DUSE_MMI_CHARGER
	EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/mmi_charger

endif

ifneq ($(filter m y, $(ADAPTIVE_TOLERANCE_OPTIMIZATION)),)
	EXTRA_CFLAGS += -DADAPTIVE_TOLERANCE_OPTIMIZATION
endif

obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE) += qpnp_adaptive_charge.o
