# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

obj-$(CONFIG_MMI_WATCHDOG_CPU_CTX) += watchdog_cpu_ctx.o




